---
name: automerge
on:
  pull_request:
    branches:
      - 'dev'
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#github-workflow'
        if: always()
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        with:
          args: "--trace"
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-workflow'
        if: always()
...
