---
name: Automerge to dev
on:
  pull_request:
    branches: 
     - '!**'
     - main
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: automerge to dev
        uses: devmasx/merge-branch@v1.3.0
        with:
          label_name: 'automerge-to-dev'
          target_branch: 'dev'
          github_token: ${{ github.token }}
...
