---
name: Merge branch with labeled
on:
  pull_request:
    branches: 
     - '!**'
     - main
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.3.0
        with:
          label_name: 'automerge-to-dev'
          target_branch: 'dev'
          github_token: ${{ github.token }}
...
