# This is a basic workflow to help you get started with Actions

name: automerge

# Controls when the action will run. Triggers the workflow on pull request
# events
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
    - submitted
  check_suite:
    types: 
    - completed
  status: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "automerge"
  automerge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: automerge
      - uses: "pascalgn/automerge-action@0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
     
